markdown: kramdown
theme: jekyll-theme-midnight
title: Notes
author: M13X
description: Storing notes

collections:
  my_collection:
    output: true
    permalink: "/Notes/Obsidian%20Vault/README.md"

#Colors

_black: '#0D1117'
_white: '#fff'

body-bg: _black
text-color: _white
